// payments Actions
export const PAYMENTS_TABLE_FORMAT = '@@PAYMENTS/TABLE/FORMAT';
export const PAYMENTS_TABLE_FILTER = '@@PAYMENTS/TABLE/FILTER';
export const PAYMENTS_TABLE_UPDATE = '@@PAYMENTS/TABLE/UPDATE';
