// payments Actions
export const PAYMENTS_TABLE_FORMAT = '@@PAYMENTS/TABLE/FORMAT';
export const PAYMENTS_TABLE_FILTER = '@@PAYMENTS/TABLE/FILTER';
export const PAYMENTS_TABLE_UPDATE = '@@PAYMENTS/TABLE/UPDATE';

export const PAYMENTS_TABLE_FILTER_BY_YEAR = '@@PAYMENTS/TABLE/FILTER_BY_YEAR';


// product Actions
export const PRODUCTS_ADD_INGREDIENT = '@@PRODUCTS/ADD/INGREDIENT';
export const PRODUCTS_REMOVE_INGREDIENT = '@@PRODUCTS/REMOVE/INGREDIENT';
export const PRODUCTS_ADD_MASS = '@@PRODUCTS/ADD/MASS';
export const PRODUCTS_REMOVE_MASS = '@@PRODUCTS/REMOVE/MASS';
export const PRODUCTS_SET_NAME = '@@PRODUCTS/SET/NAME';
export const PRODUCTS_UPDATE = '@@PRODUCTS/UPDATE';
export const PRODUCTS_SAVE = '@@PRODUCTS/SAVE';
